<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            'Ayala Greenfields',
            'Ayala Westgrove',
            'SRE 1',
            'SSI',
            'Manila Cordage',
            'Sankyo',
            'Carmel Mall',
            'Aimway Plastic & Printing Corp.',
            'CBRE - Apple',
            'ROHM',
            'Calabarzon',
            'CBRE - CORO',
            'CBRE - Transcom - Ayala 30th',
            'CBRE - EXL - Filinvest',
            'CBRE',
            'CBRE - RCM - Cubao',
            'CBRE - 6750 - Chevron',
            'CBRE - Petsure',
            'CBRE - Chevron - RCBC',
            'CBRE - EXL - Plaza E',
            'JLL - LSEG',
            'CBRE - HCL',
            'CBRE - Tenet',
            'CBRE - GWS Business Support Services',
            'DOW Chemical Philippines Inc.',
            'CBRE - Cigna',
            'CBRE - 1WS - Tenet',
            'CBRE - Tenet - World Plaza',
            'CBRE - DXC - Eton',
            'CBRE - Empower',
            'CBRE - DKS Taguig',
            'CBRE - Tenet - Eastwood',
            'CBRE - MYNT - WGC',
            'CBRE - Tenet - Bridgetowne',
            'CBRE - DXC - IPC',
            'CBRE - Tenet - ACC',
            'CBRE - Citibank - BGC',
            'CBRE - BOSCH - W Fifth',
            'CBRE - DXC - TWS',
            'Ubisoft',
            'CBRE - DBM',
            'MSD',
            'Dualtech',
            'Carmelray Park 1',
            'Metro Hue Tech',
            'NYK',
            'Techduo',
            'Rosario Business Center',
            'Junction',
            'Treveia Nuvali',
            'San Ramon/Morning Fields',
            'The Mills',
            'San Jose Village III',
            'Udenna',
            'CBRE - RCM - BGC',
            'CBRE - Syntel',
            'CBRE - Vismin - Chevron',
            'CBRE - Opella',
            'CBRE - Refinitiv',
            'CBRE - Tenet - Five Neo',
            'CBRE - Transcom - Pasig',
            'CBRE - FSL - Taguig',
            'CBRE - MYNT',
            'CBRE - JTIP - BGC',
            'CBRE - DOW',
            'CBRE - American Express',
            'CBRE - CHUBB',
            'CBRE - Bank of America',
            'CBRE - MYNT - WCC',
            'CBRE - Sanofi',
            'CBRE - FSL - Pasay',
            'CBRE - Pacific Plaza',
            'CBRE - S&P Global - Bridgetowne',
            'PADL',
            'CBRE - Honeywell',
            'CBRE - Citi Plaza - Tenet',
            'CBRE - Trafigura',
            'CBRE - W Fifth - Cx Loyalty',
            'CBRE - Siemens',
            'VS Industry Philippines Inc.',
            'CBRE - PITX',
            'CBRE - Head Office',
            'Bel Mondo Italiana Corp.',
            'Dupont',
            'CBRE - Renaissance Tower',
            'JTI',
            'CBRE - Integrated Bar of the Philippines',
            'CBRE - Finastra',
            'CBRE - Aboitiz',
            'CBRE - Macquarie',
            'CBRE - Tenet/Collabera',
            'COHU',
            'CBRE- Vestas',
            'CBRE - CIMB',
            'Metro Pacific Water',
            'Fieldcore Service Solutions International LLC',
            'ETAP - Bulacan',
            'CBRE - FirstSource Solutions Limited',
            'CBRE - Firmenich',
            'CBRE - Aggreko',
            'CBRE - MARS/WRIGLEY',
            'CBRE - EXL - Pasay',
            'CBRE - DTCC - Makati',
            'CBRE - Transcom - Iloilo',
            'CBRE - Transcom - Bacolod',
            'CBRE - TCCC',
            'CBRE - Bloomberg',
            'CBRE - Citibank - Eastwood',
            'CBRE - General Motors',
            'CBRE - BOSCH - 10 West Campus',
            'El Llave Holdings',
            'Aggreko - Laguna',
            'CBRE - Transcom - Davao Matina',
            'CBRE - Transcom - Davao Delta',
            'CBRE - Transcom - Davao Tavera',
            'CBRE - S&P Global - One Ayala',
            'CBRE - S&P Global - Silver City',
            'CBRE - AFLOW',
            'CBRE - Kenvue',
            'CBRE - JTIP - Mckinley',
            'CBRE - JTIP - Dumaguete',
            'CBRE - JTIP - Cagayan De Oro',
            'CBRE - JTIP - Palawan',
            'CBRE - JTIP - Laguna',
            'CBRE - JTIP - Tuguegarao',
            'CBRE - JTIP - Naga',
            'CBRE - JTIP - Quezon',
            'CBRE - JTIP - Capiz',
            'CBRE - JTIP - Dasmariñas',
            'CBRE - JTIP - Ozamis',
            'CBRE - JTIP - Tagum',
            'CBRE - JTIP - Iloilo',
            'CBRE - JTIP - Calapan',
            'CBRE - JTIP - Tarlac',
            'CBRE - JTIP - Zamboanga',
            'CBRE - JTIP - Tacloban',
            'CBRE - JTIP - Albay',
            'CBRE - JTIP - Talisay',
            'CBRE - JTIP - Bacolod',
            'CBRE - JTIP - General Santos',
            'CBRE - JTIP - Las Piñas',
            'CBRE - JTIP - Davao',
            'CBRE - JTIP - Valenzuela',
            'CBRE - JTIP - Isabela',
            'CBRE - JTIP - Pampanga',
            'CBRE - JTIP - Mandaue',
            'CBRE - JTIP - Rizal',
            'CBRE - JTIP - Samar',
            'CBRE - JTIP - Bohol',
            'CBRE - JTIP - Marikina',
            'CBRE - JTIP - Butuan',
            'CBRE - JTIP - Nueva Ecija',
            'CBRE - JTIP - Pangasinan',
            'CBRE - JTIP - Ilocos',
            'CBRE - JTIP - Lipa',
            'CBRE - JTIP - Sto. Tomas',
            'CBRE - FSL - Cebu',
            'CBRE - JTIP - Makati',
            'CBRE - JTIP - Bacoor',
            'CBRE - Accenture',
            'CBRE - Transcom - Giga',
            'CBRE - JTIP - Masbate',
            'CBRE - JTIP - Bukidnon',
            'CBRE - ING Bank',
            'CBRE - EXL - SM North',
            'CBRE - JTIP - Baesa',
            'CBRE - JTIP - Tagbilaran',
            'CBRE - Vestas',
            'CBRE - IGT Solutions',
            'CBRE - Emmerson',
        ];

        foreach ($sites as $site) {
            DB::table('sites')->updateOrInsert(
                [
                    'site_name' => $site,
                ],
                [
                    'site_location' => null,
                    'client_id' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}